# @package module.model
audio_processor:
  _target_: torch.nn.Identity

audio_processor_normalizer:
  _target_: torch.nn.Identity

audio_encoder:
  _target_: src.utils.hf_utils.load_nemo_model
  model_name: nvidia/speakerverification_en_titanet_large
  map_location: "cuda"

classifier:
  _target_: speechbrain.lobes.models.ECAPA_TDNN.Classifier
  input_size: 192
  out_neurons: ${datamodule.num_classes}