# @package module.model.fusion_classifier
_target_: src.modules.multimodal_vpc.FusionClassifierWithResiduals
fuse_model:
  _target_: src.modules.multimodal_vpc.NormalizedWeightedSum
  audio_embedding_size: 192
  text_embedding_size: 768
  hidden_size: 512
input_size: 512
hidden_size: 1024
num_classes: ${datamodule.num_classes}
dropout_residual: 0.3
num_residuals: 2
norm_type: 'batch'