_target_: src.datamodules.vpc_datamodule.AnonLibriDataModule

num_classes: 1001 # Number of classes in train-360-clean, dev-clean and test-clean
root_dir: ${paths.data_dir}/vpc2025_official    

dataset:
  artifacts_dir: ${paths.output_dir}/vpc2025_artifacts
  speakers_file: ${paths.data_dir}/librispeech/metadata/SPEAKERS.csv
  speaker_lookup: ${datamodule.dataset.artifacts_dir}/speaker_lookup.csv
  sep: "|"
  verbose: true
  save_csv: true
  sample_rate: 16000
  min_duration: 0.5
  max_duration: -1

artifacts_paths:
  train: ${datamodule.dataset.artifacts_dir}/train.csv
  dev: ${datamodule.dataset.artifacts_dir}/dev.csv
  test: ${datamodule.dataset.artifacts_dir}/test.csv
  dev_unique: ${datamodule.dataset.artifacts_dir}/dev_unique.csv
  test_unique: ${datamodule.dataset.artifacts_dir}/test_unique.csv
  dev_enrolls: ${datamodule.dataset.artifacts_dir}/dev_enrolls.csv
  test_enrolls: ${datamodule.dataset.artifacts_dir}/test_enrolls.csv
  dev_trials: ${datamodule.dataset.artifacts_dir}/dev_trials.csv
  test_trials: ${datamodule.dataset.artifacts_dir}/test_trials.csv
  spks_train: ${datamodule.dataset.artifacts_dir}/speakers_train.csv
  spks_dev: ${datamodule.dataset.artifacts_dir}/speakers_dev.csv
  spks_test: ${datamodule.dataset.artifacts_dir}/speakers_test.csv

available_models:
  B3:
    data_dir: ${datamodule.root_dir}/B3/data   
    metadata: ${datamodule.available_models.B3.data_dir}/metadata
    train: ${datamodule.available_models.B3.metadata}/train.csv
    dev: ${datamodule.available_models.B3.metadata}/dev.csv
    test: ${datamodule.available_models.B3.metadata}/test.csv
    dev_enrolls: ${datamodule.available_models.B3.metadata}/dev_enrolls.csv
    test_enrolls: ${datamodule.available_models.B3.metadata}/test_enrolls.csv
    dev_trials: ${datamodule.available_models.B3.metadata}/dev_trials.csv
    test_trials: ${datamodule.available_models.B3.metadata}/test_trials.csv
  B4:
    data_dir: ${datamodule.root_dir}/B4/data
    metadata: ${datamodule.available_models.B4.data_dir}/metadata
    train: ${datamodule.available_models.B4.metadata}/train.csv
    dev: ${datamodule.available_models.B4.metadata}/dev.csv
    test: ${datamodule.available_models.B4.metadata}/test.csv
    dev_enrolls: ${datamodule.available_models.B4.metadata}/dev_enrolls.csv
    test_enrolls: ${datamodule.available_models.B4.metadata}/test_enrolls.csv
    dev_trials: ${datamodule.available_models.B4.metadata}/dev_trials.csv
    test_trials: ${datamodule.available_models.B4.metadata}/test_trials.csv
  B5:
    data_dir: ${datamodule.root_dir}/B5/data
    metadata: ${datamodule.available_models.B5.data_dir}/metadata
    train: ${datamodule.available_models.B5.metadata}/train.csv
    dev: ${datamodule.available_models.B5.metadata}/dev.csv
    test: ${datamodule.available_models.B5.metadata}/test.csv
    dev_enrolls: ${datamodule.available_models.B5.metadata}/dev_enrolls.csv
    test_enrolls: ${datamodule.available_models.B5.metadata}/test_enrolls.csv
    dev_trials: ${datamodule.available_models.B5.metadata}/dev_trials.csv
    test_trials: ${datamodule.available_models.B5.metadata}/test_trials.csv
  T8-5:
    data_dir: ${datamodule.root_dir}/T8-5/data
    metadata: ${datamodule.available_models.T8-5.data_dir}/metadata
    train: ${datamodule.available_models.T8-5.metadata}/train.csv
    dev: ${datamodule.available_models.T8-5.metadata}/dev.csv
    test: ${datamodule.available_models.T8-5.metadata}/test.csv
    dev_enrolls: ${datamodule.available_models.T8-5.metadata}/dev_enrolls.csv
    test_enrolls: ${datamodule.available_models.T8-5.metadata}/test_enrolls.csv
    dev_trials: ${datamodule.available_models.T8-5.metadata}/dev_trials.csv
    test_trials: ${datamodule.available_models.T8-5.metadata}/test_trials.csv
  T12-5:
    data_dir: ${datamodule.root_dir}/T12-5/data
    metadata: ${datamodule.available_models.T12-5.data_dir}/metadata
    train: ${datamodule.available_models.T12-5.metadata}/train.csv
    dev: ${datamodule.available_models.T12-5.metadata}/dev.csv
    test: ${datamodule.available_models.T12-5.metadata}/test.csv
    dev_enrolls: ${datamodule.available_models.T12-5.metadata}/dev_enrolls.csv
    test_enrolls: ${datamodule.available_models.T12-5.metadata}/test_enrolls.csv
    dev_trials: ${datamodule.available_models.T12-5.metadata}/dev_trials.csv
    test_trials: ${datamodule.available_models.T12-5.metadata}/test_trials.csv
  T25-1:
    data_dir: ${datamodule.root_dir}/T25-1/data
    metadata: ${datamodule.available_models.T25-1.data_dir}/metadata
    train: ${datamodule.available_models.T25-1.metadata}/train.csv
    dev: ${datamodule.available_models.T25-1.metadata}/dev.csv
    test: ${datamodule.available_models.T25-1.metadata}/test.csv
    dev_enrolls: ${datamodule.available_models.T25-1.metadata}/dev_enrolls.csv
    test_enrolls: ${datamodule.available_models.T25-1.metadata}/test_enrolls.csv
    dev_trials: ${datamodule.available_models.T25-1.metadata}/dev_trials.csv
    test_trials: ${datamodule.available_models.T25-1.metadata}/test_trials.csv

# for all models use: #${datamodule.available_models}); override via command line datamodule.models={B3: ${datamodule.available_models.B3}}
models: ???

transform: null

loaders:
  train:
    batch_size: 16
    shuffle: True
    num_workers: 4
    drop_last: True
    pin_memory: False
  valid:
    batch_size: 16
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False
  test:
    batch_size: 8
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False
  enrollment:
    batch_size: 1 # 1 for enrollment
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False
